#
# mojoproject.toml
# mosaic
#
# Created by Christian Bator on 03/11/2025
#

[project]
# These should match rattler-build/recipe.yaml > context
version = "0.0.1"

# These should match rattler-build/recipe.yaml > about
homepage = "https://mosaiclib.org"
license = "Apache-2.0"
license-file = "LICENSE"
description = "An open source computer vision library in Mojo" # This is "summary" in recipe.yaml
repository = "https://github.com/christianbator/mosaic"
documentation = "https://mosaiclib.org/docs"

# These should match rattler-build/recipe.yaml > extra
name = "mosaic"
authors = ["Christian Bator <christian@bator.co>"]

# These are only defined here
readme = "README.md"
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]
channels = [
    "https://conda.modular.com/max-nightly",
    "https://conda.modular.com/max",
    "conda-forge"
]

[dependencies]
max = "~=25.1"

[system-requirements]
macos = "15"
linux = "6.8"

[target.osx.activation.env]
PREFIX = "$PIXI_PROJECT_ROOT/build"
SHLIB_EXT = ".dylib"

[target.linux.activation.env]
PREFIX = "$PIXI_PROJECT_ROOT/build"
SHLIB_EXT = ".so"

[tasks]
build = { cmd = "build/build.sh" }
test = { cmd = "mojo test", depends-on = ["build"], cwd = "test" }
format = { cmd = "mojo format --line-length 160 mosaic test examples" }
