#
# mojoproject.toml
# mosaic
#
# Created by Christian Bator on 03/11/2025
#

[project]
name = "mosaic"
version = "0.0.1"
description = "Vision of the future"
authors = ["Christian Bator <christian@bator.co>"]
platforms = ["osx-arm64"]
channels = [
    "https://conda.modular.com/max-nightly",
    "https://conda.modular.com/max",
    "https://repo.prefix.dev/modular-community", 
    "conda-forge"
]

[dependencies]
max = "=25.2.0"

[tasks]
build = { cmd = "build/build.sh" }
test = { cmd = "mojo test", depends-on = ["build"], cwd = "test" }
format = { cmd = "mojo format --line-length 160 mosaic test examples" }
