#
# mojoproject.toml
# mosaic
#
# Created by Christian Bator on 03/11/2025
#

[project]
name = "mosaic"
description = "An open source computer vision library in Mojo"
authors = ["Christian Bator <christian@bator.co>"]
readme = "README.md"
license = "Apache-2.0"
license-file = "LICENSE"
homepage = "https://mosaiclib.org"
repository = "https://github.com/christianbator/mosaic"
documentation = "https://mosaiclib.org/docs"
version = "0.0.1"
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]
channels = [
    "https://conda.modular.com/max-nightly",
    "https://conda.modular.com/max",
    "conda-forge"
]

[dependencies]
max = "~=25.1"

[tasks]
build = { cmd = "build/build.sh" }
test = { cmd = "mojo test", depends-on = ["build"], cwd = "test" }
format = { cmd = "mojo format --line-length 160 mosaic test examples" }
