#!/usr/bin/env bash

#
# pre-commit
# mosaic
#
# Created by Christian Bator on 03/15/2025
#

# Colors
cyan="\033[36m"
reset="\033[0m"

# Run the format command and capture its output
output=$(magic run format 2>&1)
echo "$output"

# Look for files that were reformatted in the output: "reformatted <filepath>"
reformatted_files=$(echo $output | grep -Eo "reformatted [^[:space:]]+\.mojo" | cut -d " " -f 2)

# If no reformatted files are found, proceed with the commit
if [ -z "$reformatted_files" ]; then
  exit 0
fi

# Loop through the reformatted files
for file in $reformatted_files; do
  # Check if the file is staged
  if git diff --name-only --staged | grep -q "$file"; then
    echo "Adding reformatted file: $file ..."
    git add "$file"
  fi
done

# Perform the commit again, this time with the reformatted files
# echo "Committing with reformatted files ..."
# git commit --amend --no-edit

exit 0
