#!/usr/bin/env bash

#
# pre-commit
# mosaic
#
# Created by Christian Bator on 03/15/2025
#

# Run the format command and capture its output
output=$(magic run format 2>&1)
echo -e "$output\n"

# Look for files that were reformatted in the output: "reformatted <filepath>"
reformatted_files=$(echo $output | grep -Eo "reformatted [^[:space:]]+\.mojo" | cut -d " " -f 2)

if [ -z "$reformatted_files" ]; then
    # If no reformatted files are found, proceed with the commit
    exit 0
else
    # Otherwise, re-add reformatted files    
    for file in $reformatted_files; do
        if git diff --name-only --staged | grep -q "$file"; then
            git add "$file"
        fi
    done
fi
