#
# rattler-build.yml
# mosaic
#
# Created by Christian Bator on 03/17/2025
#


name: Rattler Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target-platform: osx-arm64
          - os: ubuntu-24.04-arm
            target-platform: linux-aarch64
          - os: ubuntu-latest
            target-platform: linux-64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build package
        uses: prefix-dev/rattler-build-action@v0.2.33
        with:
          recipe-path: rattler-build/recipe.yaml
          build-args: --target-platform ${{ matrix.target-platform }} -c https://conda.modular.com/max-nightly -c https://conda.modular.com/max -c conda-forge
          artifact-name: mosaic-${{ matrix.target-platform }}
