#
# rattler-build.yml
# mosaic
#
# Created by Christian Bator on 03/17/2025
#


name: Rattler Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target-platform: osx-64
          - os: macos-14
            target-platform: osx-arm64
          - os: ubuntu-latest
            target-platform: linux-64
          - os: ubuntu-latest
            target-platform: linux-aarch64    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install rattler-build (Unix)
        shell: bash
        if: ${{ runner.os != 'Windows' }}
        run: |
          mkdir -p ${{ runner.temp }}/rattler-build
          curl -Ls \
            ${{ steps.url.outputs.url }} \
            -o ${{ runner.temp }}/rattler-build/rattler-build
          chmod +x ${{ runner.temp }}/rattler-build/rattler-build
          echo ${{ runner.temp }}/rattler-build >> $GITHUB_PATH
      - name: Build package
        shell: bash
        working-directory: rattler-build
        if: ${{ runner.os != 'Windows' }}
        run: rattler-build build -c https://conda.modular.com/max-nightly -c conda-forge --recipe recipe.yaml
        env:
          RATTLER_BUILD_ENABLE_GITHUB_INTEGRATION: 'true'
          RATTLER_BUILD_COLOR: 'always'
