#
# rattler-build.yml
# mosaic
#
# Created by Christian Bator on 03/17/2025
#


name: Rattler Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target-platform: osx-64
          - os: macos-14
            target-platform: osx-arm64
          - os: ubuntu-latest
            target-platform: linux-64
          - os: ubuntu-latest
            target-platform: linux-aarch64    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build package
        working-directory: rattler-build
        uses: prefix-dev/rattler-build-action@v0.2.33
        with:
          recipe-path: recipe.yaml
          build-args: -c https://conda.modular.com/max -c conda-forge --target-platform ${{ matrix.target-platform }}${{ matrix.target-platform == 'linux-aarch64' && ' --no-test' || '' }}
          artifact-name: mosaic-${{ matrix.target-platform }}
      
    
